services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontaiermoveilist
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database_movielist:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: mymovielist
      MYSQL_USER: admin
      MYSQL_PASSWORD: Pass_1122
      MYSQL_ROOT_PASSWORD: Pass_1122
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internamymovielistnet

  nodeapp:
    container_name: nodeappcontainermymovielist
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: 'mysqlcontaiermymovielist'
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'Pass_1122'
      DB_NAME: mymovielist
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internamymovielistnet

networks:
  internamymovielistnet:
    driver: bridge
